{% set name = "gomi" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/babarot/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9cdf4ec51e6629573bcec7779e1b30e0bafbbe10d499cc2e7bbae46a6b3d3621

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - gomi --help

about:
  home: https://gomi.dev/
  dev_url: https://github.com/babarot/gomi
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A UNIX rm command with a safety net
extra:
  recipe-maintainers:
    - apcamargo
