{% set name = "gomi" %}
{% set version = "1.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/babarot/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 27d4bfca8473a5c01c3ead075f2674b47b586b6de8afc7fb31ade1c01d7e5b8a

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - gomi --help

about:
  home: https://gomi.dev/
  dev_url: https://github.com/babarot/gomi
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A UNIX rm command with a safety net
extra:
  recipe-maintainers:
    - apcamargo
